test_gpu_vs_f32: tools/vault/test_gpu_vs_f32.cu src/cuda_kernels.o src/gpu_quant_matmul.o src/gguf_reader.o src/dequant_iq2_xxs.o src/wubu_ssm.o
	$(NVCC) $(NVCC_FLAGS) -c tools/vault/test_gpu_vs_f32.cu -o tools/vault/test_gpu_vs_f32.o
	g++ -O3 -I include -I/usr/local/cuda-13.1/include -o $@ tools/vault/test_gpu_vs_f32.o src/cuda_kernels.o src/gpu_quant_matmul.o src/gguf_reader.o src/dequant_iq2_xxs.o src/wubu_ssm.o -L/usr/local/cuda-13.1/lib64 -lcudart -lcublas -lm -fopenmp
