@echo OFF
SETLOCAL ENABLEDELAYEDEXPANSION

SET "PROJECT_ROOT=%~dp0.."
IF EXIST "%PROJECT_ROOT%\venv\Scripts\python.exe" (
    SET "PYTHON_EXE=%PROJECT_ROOT%\venv\Scripts\python.exe"
) ELSE IF EXIST "%PROJECT_ROOT%\.venv\Scripts\python.exe" (
    SET "PYTHON_EXE=%PROJECT_ROOT%\.venv\Scripts\python.exe"
) ELSE (
    SET "PYTHON_EXE=python"
)
SET "SCRIPT_DIR=%~dp0"
SET "SCRIPT_NAME=WuBuCPUOnlyGen_v1.py"
SET "FULL_SCRIPT_PATH=%SCRIPT_DIR%%SCRIPT_NAME%"

SET "DATA_DIR_BASE=%PROJECT_ROOT%\data"
SET "CHECKPOINT_OUTPUT_DIR=%PROJECT_ROOT%\checkpoints\WuBuCPUOnlyGen_v1_Run_Latest_Adv"
SET "VIDEO_DATA_PATH=%DATA_DIR_BASE%\demo_video_data_cpu"
SET "LOAD_CHECKPOINT="
SET "LATEST_EPOCH_CKPT_NAME="

IF EXIST "%CHECKPOINT_OUTPUT_DIR%" (
    FOR /F "delims=" %%F IN ('dir /b /o-d /a-d "%CHECKPOINT_OUTPUT_DIR%\wubucpu_gen_v1_ep*_step*.pt"') DO (
        SET "LATEST_EPOCH_CKPT_NAME=%%F"
        GOTO FoundLatestEpochCkpt_CPU
    )
    :FoundLatestEpochCkpt_CPU
    IF DEFINED LATEST_EPOCH_CKPT_NAME (
        IF NOT "%LATEST_EPOCH_CKPT_NAME%"=="" SET "LOAD_CHECKPOINT=%CHECKPOINT_OUTPUT_DIR%\!LATEST_EPOCH_CKPT_NAME!"
    )
)

SET "IMAGE_H=256"
SET "IMAGE_W=256"
SET "NUM_CHANNELS=3"
SET "NUM_INPUT_FRAMES=2"
SET "NUM_PREDICT_FRAMES=1"
SET "FRAME_SKIP=1"
SET "LATENT_DIM=512"
SET "PATCH_SIZE_H=4"
SET "PATCH_SIZE_W=4"

SET "GAAD_NUM_REGIONS=256"
SET "GAAD_MIN_SIZE_PX=4"

SET "WUBU_INITIAL_S=1.0"
SET "WUBU_S_DECAY=0.9999"
SET "WUBU_INITIAL_C=0.1"
SET "WUBU_C_PHI_INFLUENCE=true"
SET "WUBU_NUM_PHI_SCAFFOLD_POINTS=7"
SET "WUBU_PHI_SCAFFOLD_INIT_SCALE=0.001"
SET "WUBU_USE_GAUSSIAN_RUNGS=true"
SET "WUBU_BASE_GAUSSIAN_STD_DEV=0.005"
SET "WUBU_GAUSSIAN_STD_DEV_DECAY=0.999995"
SET "WUBU_RUNG_AFFINITY_TEMP=0.01"
SET "WUBU_RUNG_MODULATION_STRENGTH=0.001"
SET "WUBU_T_TILDE_SCALE=1.00001"
SET "WUBU_MICRO_TRANSFORM_TYPE=mlp"
SET "WUBU_MICRO_TRANSFORM_HIDDEN_FACTOR=0.5"
SET "WUBU_USE_QUATERNION_SO4=true"
SET "WUBU_SCAFFOLD_CO_ROTATION_MODE=none"

SET "WUBU_ENABLE_ISP=true"
SET "WUBU_ENABLE_STATEFUL=true"
SET "WUBU_ENABLE_HYPERNET=true"
SET "WUBU_INTERNAL_STATE_FACTOR=0.5"
SET "WUBU_HYPERNET_STRENGTH=0.01"

SET "ENC_WUBU_NUM_VIRTUAL_LEVELS=5000"
SET "ENC_WUBU_BASE_MICRO_DIM=4"
SET "ENC_WUBU_NUM_PHYSICAL_STAGES=125"

SET "GEN_WUBU_NUM_VIRTUAL_LEVELS=10000"
SET "GEN_WUBU_BASE_MICRO_DIM=4"
SET "GEN_WUBU_NUM_PHYSICAL_STAGES=250"

SET "DISC_WUBU_NUM_VIRTUAL_LEVELS=5000"
SET "DISC_WUBU_BASE_MICRO_DIM=4"
SET "DISC_WUBU_NUM_PHYSICAL_STAGES=125"

SET "EPOCHS=5000"
SET "BATCH_SIZE=512"
SET "LEARNING_RATE_GEN=1e-4"
SET "LEARNING_RATE_DISC=1e-4"
SET "TRAIN_SEED=42"
SET "TRAIN_NUM_WORKERS=8"

SET "LAMBDA_RECON=10.0"
SET "LAMBDA_KL=0.01"
SET "LAMBDA_GAN=1.0"

SET "LOG_INTERVAL=1"
SET "SAVE_INTERVAL=1"
SET "SHOW_TRAIN_PROGRESS_BAR=true"
SET "WANDB_LOG_TRAIN_RECON_INTERVAL=1"
SET "WANDB_LOG_FIXED_NOISE_SAMPLES_INTERVAL=1"
SET "NUM_VAL_SAMPLES_TO_LOG=2"
SET "DATA_FRACTION=1.0"
SET "LOAD_CHECKPOINT_RESET_EPOCH=false"

SET "VAL_FRACTION=0.1"
SET "VAL_BATCH_SIZE="
SET "VALIDATE_EVERY_N_EPOCHS=1"
SET "WANDB_LOG_VAL_RECON_INTERVAL_EPOCHS=1"

SET "WANDB_ENABLED=true"
SET "WANDB_PROJECT=WuBuCPUGenV1Adv"
SET "WANDB_RUN_NAME="

SET "SCRIPT_ARGS="
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --video_data_path "%VIDEO_DATA_PATH%""
IF DEFINED LOAD_CHECKPOINT (
    IF NOT "%LOAD_CHECKPOINT%"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --load_checkpoint "%LOAD_CHECKPOINT%""
)
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --checkpoint_dir "%CHECKPOINT_OUTPUT_DIR%""
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --image_h %IMAGE_H%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --image_w %IMAGE_W%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --num_channels %NUM_CHANNELS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --num_input_frames %NUM_INPUT_FRAMES%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --num_predict_frames %NUM_PREDICT_FRAMES%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --frame_skip %FRAME_SKIP%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --latent_dim %LATENT_DIM%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --patch_size_h %PATCH_SIZE_H%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --patch_size_w %PATCH_SIZE_W%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --gaad_num_regions %GAAD_NUM_REGIONS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --gaad_min_size_px %GAAD_MIN_SIZE_PX%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_initial_s %WUBU_INITIAL_S%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_decay %WUBU_S_DECAY%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_initial_c %WUBU_INITIAL_C%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_c_phi_influence %WUBU_C_PHI_INFLUENCE%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_num_phi_scaffold_points %WUBU_NUM_PHI_SCAFFOLD_POINTS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_phi_scaffold_init_scale %WUBU_PHI_SCAFFOLD_INIT_SCALE%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_use_gaussian_rungs %WUBU_USE_GAUSSIAN_RUNGS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_base_gaussian_std_dev %WUBU_BASE_GAUSSIAN_STD_DEV%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_gaussian_std_dev_decay %WUBU_GAUSSIAN_STD_DEV_DECAY%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_rung_affinity_temp %WUBU_RUNG_AFFINITY_TEMP%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_rung_modulation_strength %WUBU_RUNG_MODULATION_STRENGTH%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_t_tilde_scale %WUBU_T_TILDE_SCALE%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_micro_transform_type %WUBU_MICRO_TRANSFORM_TYPE%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_micro_transform_hidden_factor %WUBU_MICRO_TRANSFORM_HIDDEN_FACTOR%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_use_quaternion_so4 %WUBU_USE_QUATERNION_SO4%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_scaffold_co_rotation_mode %WUBU_SCAFFOLD_CO_ROTATION_MODE%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_enable_isp %WUBU_ENABLE_ISP%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_enable_stateful %WUBU_ENABLE_STATEFUL%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_enable_hypernet %WUBU_ENABLE_HYPERNET%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_internal_state_factor %WUBU_INTERNAL_STATE_FACTOR%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_hypernet_strength %WUBU_HYPERNET_STRENGTH%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --enc_wubu_num_virtual_levels %ENC_WUBU_NUM_VIRTUAL_LEVELS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --enc_wubu_base_micro_dim %ENC_WUBU_BASE_MICRO_DIM%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --enc_wubu_num_physical_stages %ENC_WUBU_NUM_PHYSICAL_STAGES%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --gen_wubu_num_virtual_levels %GEN_WUBU_NUM_VIRTUAL_LEVELS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --gen_wubu_base_micro_dim %GEN_WUBU_BASE_MICRO_DIM%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --gen_wubu_num_physical_stages %GEN_WUBU_NUM_PHYSICAL_STAGES%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_wubu_num_virtual_levels %DISC_WUBU_NUM_VIRTUAL_LEVELS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_wubu_base_micro_dim %DISC_WUBU_BASE_MICRO_DIM%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_wubu_num_physical_stages %DISC_WUBU_NUM_PHYSICAL_STAGES%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --epochs %EPOCHS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --batch_size %BATCH_SIZE%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --learning_rate_gen %LEARNING_RATE_GEN%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --learning_rate_disc %LEARNING_RATE_DISC%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --seed %TRAIN_SEED%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --num_workers %TRAIN_NUM_WORKERS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --lambda_recon %LAMBDA_RECON%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --lambda_kl %LAMBDA_KL%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --lambda_gan %LAMBDA_GAN%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --log_interval %LOG_INTERVAL%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --save_interval %SAVE_INTERVAL%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --show_train_progress_bar %SHOW_TRAIN_PROGRESS_BAR%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb_log_train_recon_interval %WANDB_LOG_TRAIN_RECON_INTERVAL%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb_log_fixed_noise_samples_interval %WANDB_LOG_FIXED_NOISE_SAMPLES_INTERVAL%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --num_val_samples_to_log %NUM_VAL_SAMPLES_TO_LOG%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --data_fraction %DATA_FRACTION%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --load_checkpoint_reset_epoch %LOAD_CHECKPOINT_RESET_EPOCH%"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --val_fraction %VAL_FRACTION%"
IF DEFINED VAL_BATCH_SIZE (
    IF NOT "%VAL_BATCH_SIZE%"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --val_batch_size %VAL_BATCH_SIZE%"
)
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --validate_every_n_epochs %VALIDATE_EVERY_N_EPOCHS%"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb_log_val_recon_interval_epochs %WANDB_LOG_VAL_RECON_INTERVAL_EPOCHS%"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb %WANDB_ENABLED%"
IF /I "%WANDB_ENABLED%"=="true" (
    SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb_project %WANDB_PROJECT%"
    IF DEFINED WANDB_RUN_NAME (
        IF NOT "%WANDB_RUN_NAME%"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb_run_name "%WANDB_RUN_NAME%""
    )
)

ECHO ======================================================
ECHO WuBuCPUOnlyGen V1 - CPU Execution (Advanced FDQWR)
ECHO Python: %PYTHON_EXE%
ECHO Script Name: %SCRIPT_NAME%
ECHO Checkpoints: %CHECKPOINT_OUTPUT_DIR%
ECHO Latent Dim: %LATENT_DIM%
ECHO Image Size: %IMAGE_H%x%IMAGE_W%
ECHO WANDB: %WANDB_ENABLED%
ECHO Advanced Features: ISP=%WUBU_ENABLE_ISP%, Stateful=%WUBU_ENABLE_STATEFUL%, HyperNet=%WUBU_ENABLE_HYPERNET%
ECHO Reset Epoch on Load: %LOAD_CHECKPOINT_RESET_EPOCH%
ECHO Validation Fraction: %VAL_FRACTION%
ECHO ======================================================
ECHO.

IF NOT EXIST "%PYTHON_EXE%" (
    ECHO ERROR: Python executable not found at %PYTHON_EXE%
    GOTO :End
)
ECHO.
IF NOT EXIST "%CHECKPOINT_OUTPUT_DIR%" MKDIR "%CHECKPOINT_OUTPUT_DIR%"
IF NOT EXIST "%DATA_DIR_BASE%" MKDIR "%DATA_DIR_BASE%"
IF NOT EXIST "%VIDEO_DATA_PATH%" MKDIR "%VIDEO_DATA_PATH%"
ECHO.

ECHO Starting CPU training script: %SCRIPT_NAME%
ECHO.
"%PYTHON_EXE%" "%FULL_SCRIPT_PATH%" !SCRIPT_ARGS!

SET "EXIT_CODE=%ERRORLEVEL%"
ECHO.
IF %EXIT_CODE% NEQ 0 (
    ECHO * SCRIPT FAILED with exit code %EXIT_CODE% *
) ELSE (
    ECHO * SCRIPT FINISHED successfully *
)

:End
TIMEOUT /T 25 /NOBREAK >nul
ENDLOCAL