@echo OFF
SETLOCAL ENABLEDELAYEDEXPANSION

REM ############################################################################
REM # SECTION: Project Paths & Python Environment
REM ############################################################################
SET "PROJECT_ROOT=%~dp0.."
SET "SCRIPT_DIR=%~dp0"
SET "SCRIPT_NAME=WuBuSpecTrans_v0.1.1.py"
SET "FULL_SCRIPT_PATH=%SCRIPT_DIR%%SCRIPT_NAME%"
SET "DATA_DIR_BASE=%PROJECT_ROOT%\data"
SET "CHECKPOINT_OUTPUT_DIR_BASE=%PROJECT_ROOT%\checkpoints"

IF EXIST "%PROJECT_ROOT%\venv\Scripts\python.exe" (
    SET "PYTHON_EXE=%PROJECT_ROOT%\venv\Scripts\python.exe"
) ELSE IF EXIST "%PROJECT_ROOT%\.venv\Scripts\python.exe" (
    SET "PYTHON_EXE=%PROJECT_ROOT%\.venv\Scripts\python.exe"
) ELSE (
    SET "PYTHON_EXE=python"
)

REM ############################################################################
REM # SECTION: Run Configuration & Checkpoint Management
REM ############################################################################
SET "RUN_NAME_SUFFIX=Run_DFT_AllIn_v2"
SET "CHECKPOINT_OUTPUT_DIR=%CHECKPOINT_OUTPUT_DIR_BASE%\WuBuSpecTrans_v011_%RUN_NAME_SUFFIX%"
SET "LOAD_CHECKPOINT_VALUE="
SET "BEST_CKPT_NAME=wubuspectrans_ckpt_v011_best.pt"
SET "LATEST_EPOCH_CKPT_NAME="

IF EXIST "%CHECKPOINT_OUTPUT_DIR%\%BEST_CKPT_NAME%" (
    SET "LOAD_CHECKPOINT_VALUE=%CHECKPOINT_OUTPUT_DIR%\%BEST_CKPT_NAME%"
) ELSE (
    FOR /F "delims=" %%F IN ('dir /b /o-d /a-d "%CHECKPOINT_OUTPUT_DIR%\wubuspectrans_ckpt_v011_ep*_step*.pt"') DO (
        SET "LATEST_EPOCH_CKPT_NAME=%%F"
        GOTO FoundLatestEpochCkpt_AllInDFTv2
    )
    :FoundLatestEpochCkpt_AllInDFTv2
    IF DEFINED LATEST_EPOCH_CKPT_NAME (
        SET "LOAD_CHECKPOINT_VALUE=%CHECKPOINT_OUTPUT_DIR%\!LATEST_EPOCH_CKPT_NAME!"
    )
)

REM ############################################################################
REM # SECTION: Core Training & Model Hyperparameters
REM ############################################################################
SET "EPOCHS=3000"
SET "GLOBAL_BATCH_SIZE=16"
SET "NPROC_PER_NODE=1"
SET "BATCH_SIZE_PER_GPU=%GLOBAL_BATCH_SIZE%"
IF %NPROC_PER_NODE% GTR 1 (
    SET /A BATCH_SIZE_PER_GPU = GLOBAL_BATCH_SIZE / NPROC_PER_NODE
    IF !BATCH_SIZE_PER_GPU! LSS 1 SET "BATCH_SIZE_PER_GPU=1"
)
SET "GRAD_ACCUM_STEPS=1"
SET "LEARNING_RATE_GEN=2.5e-5"
SET "LEARNING_RATE_DISC=7.5e-5"
SET "LEARNING_RATE_DISC_ALT=7e-5"
SET "RISGD_MAX_GRAD_NORM=2.5"
SET "GLOBAL_MAX_GRAD_NORM=4.0"

SET "LATENT_DIM=1024"
SET "ENCODER_INITIAL_TANGENT_DIM=384"

REM ############################################################################
REM # SECTION: Loss Weights
REM ############################################################################
SET "LAMBDA_RECON=12.0"
SET "LAMBDA_KL=1.5e-3"
SET "LAMBDA_GAN=1.2"

REM ############################################################################
REM # SECTION: Audio Processing & Dataset
REM ############################################################################
SET "AUDIO_DATA_PATH=%DATA_DIR_BASE%\high_quality_audio_diverse_genre_44k"
SET "VALIDATION_AUDIO_PATH=%DATA_DIR_BASE%\high_quality_audio_validation_set_44k"
SET "SAMPLE_RATE=44100"
SET "N_FFT=2048"
SET "HOP_LENGTH=256"
SET "N_MELS=256"
SET "FMIN=20.0"
SET "FMAX=20000.0"
SET "SEGMENT_DURATION_SEC=1.0"
SET "SEGMENT_OVERLAP_SEC=0.0"
SET "DB_NORM_MIN=-100.0"
SET "DB_NORM_MAX=0.0"
SET "PRELOAD_AUDIO_DATASET_TO_RAM_FLAG=true"
SET "DATASET_YIELD_RAW_AUDIO_FLAG=true"
SET "VALIDATION_SPLIT_FRACTION=0.01"
SET "DATA_FRACTION=1.0"

REM ############################################################################
REM # SECTION: GAAD & VAE Feature Transform
REM ############################################################################
SET "GAAD_NUM_REGIONS=256"
SET "GAAD_DECOMP_TYPE=hybrid"
SET "GAAD_MIN_SIZE_PX=2"
SET "REGION_PROC_SIZE_T=32"
SET "REGION_PROC_SIZE_F=32"

SET "VAE_TRANSFORM_TYPE=complex_dft_ri"
SET "DFT_FFT_NORM=ortho"
SET "DFT_COMPLEX_NORM_SCALE=80.0"

SET "DCT_NORM_TYPE_IF_USED=tanh"
SET "DCT_NORM_GLOBAL_SCALE_IF_USED=200.0"
SET "DCT_NORM_TANH_SCALE_IF_USED=60.0"

REM ############################################################################
REM # SECTION: Discriminator Architecture Variants & General Settings
REM ############################################################################
SET "DISC_APPLY_SPECTRAL_NORM_FLAG=true"
SET "PRIMARY_DISC_ARCHITECTURE_VARIANT=multi_modal_wudio_mel"
SET "ALT_DISC_ARCHITECTURE_VARIANT=global_wubu_dct"

REM # Default D settings (used if variant is 'default' for a D)
SET "DISC_INPUT_TYPE_DEFAULT=mel"
SET "DISC_BASE_DISC_CHANNELS_DEFAULT=96"
SET "DISC_MAX_DISC_CHANNELS_DEFAULT=768"
SET "DISC_TARGET_FINAL_FEATURE_DIM_H_DEFAULT=6"
SET "DISC_TARGET_FINAL_FEATURE_DIM_W_DEFAULT=6"
SET "MAX_MEL_DISC_DOWNSAMPLE_LAYERS_DEFAULT=5"
SET "USE_MEL_D_ATTENTION_DEFAULT=true"
SET "MEL_D_ATTENTION_IDX_DEFAULT=2"
SET "MEL_D_MSD_NUM_SCALES_DEFAULT=3"
SET "MEL_D_MSD_SHARE_WEIGHTS_DEFAULT=false"
SET "DISC_DCT_EMBED_DIM_DEFAULT=192"
SET "DISC_DCT_USE_POS_EMBED_DEFAULT=true"
SET "DISC_DCT_USE_CLS_TOKEN_DEFAULT=true"
SET "DISC_TRANSFORMER_NHEAD_DEFAULT=8"
SET "DISC_TRANSFORMER_DIM_FEEDFORWARD_DEFAULT=1536"
SET "DISC_TRANSFORMER_DROPOUT_DEFAULT=0.05"
SET "DISC_TRANSFORMER_NUM_LAYERS_DEFAULT=4"
SET "DISC_TRANSFORMER_NORM_FIRST_DEFAULT=true"
SET "DISC_USE_GLOBAL_STATS_AUX_DEFAULT=true"
SET "DISC_GLOBAL_STATS_MLP_HIDDEN_DIM_DEFAULT=64"

REM ############################################################################
REM # SECTION: WuBu Stack Configurations
REM ############################################################################
SET "WUBU_DROPOUT=0.05"

SET "WUBU_S_NUM_LEVELS=5"
SET "WUBU_S_HYPERBOLIC_DIMS=384 256 192 128 96"
SET "WUBU_S_INITIAL_CURVATURES=0.95 0.8 0.7 0.6 0.5"
SET "WUBU_S_INITIAL_SCALES=1.2 1.1 1.0 0.9 0.8"
SET "WUBU_S_INITIAL_SPREAD_VALUES=0.05 0.07 0.1 0.12 0.15"
SET "WUBU_S_BOUNDARY_POINTS_PER_LEVEL=8 6 4 2 0"
SET "WUBU_S_USE_ROTATION_FLAG=true"
SET "WUBU_S_PHI_INFLUENCE_CURVATURE_FLAG=true"
SET "WUBU_S_PHI_INFLUENCE_ROTATION_INIT_FLAG=true"
SET "WUBU_S_OUTPUT_DIM_ENCODER=768"

SET "WUBU_G_NUM_LEVELS=5"
SET "WUBU_G_HYPERBOLIC_DIMS=256 384 512 768 869"
SET "WUBU_G_INITIAL_CURVATURES=0.5 0.6 0.7 0.8 0.95"
SET "WUBU_G_INITIAL_SCALES=0.8 0.9 1.0 1.1 1.2"
SET "WUBU_G_INITIAL_SPREAD_VALUES=0.15 0.12 0.1 0.07 0.05"
SET "WUBU_G_BOUNDARY_POINTS_PER_LEVEL=0 2 4 6 8"
SET "WUBU_G_USE_ROTATION_FLAG=true"
SET "WUBU_G_PHI_INFLUENCE_CURVATURE_FLAG=true"
SET "WUBU_G_PHI_INFLUENCE_ROTATION_INIT_FLAG=true"

SET "WUBU_D_REGION_NUM_LEVELS=3"
SET "WUBU_D_REGION_FEATURE_DIM=192"
SET "WUBU_D_REGION_HYPERBOLIC_DIMS=192 160 128"
SET "WUBU_D_REGION_INITIAL_CURVATURES=0.7 0.5 0.3"
SET "WUBU_D_REGION_INITIAL_SCALES=1.0 0.9 0.8"
SET "WUBU_D_REGION_INITIAL_SPREAD_VALUES=0.1 0.12 0.15"
SET "WUBU_D_REGION_BOUNDARY_POINTS_PER_LEVEL=4 2 0"
SET "WUBU_D_REGION_USE_ROTATION_FLAG=true"
SET "WUBU_D_REGION_PHI_INFLUENCE_CURVATURE_FLAG=true"
SET "WUBU_D_REGION_PHI_INFLUENCE_ROTATION_INIT_FLAG=true"

SET "WUBU_D_GLOBAL_NUM_LEVELS=4"
SET "WUBU_D_GLOBAL_HYPERBOLIC_DIMS=512 384 256 192"
SET "WUBU_D_GLOBAL_INITIAL_CURVATURES=0.9 0.75 0.6 0.45"
SET "WUBU_D_GLOBAL_INITIAL_SCALES=1.1 1.0 0.9 0.8"
SET "WUBU_D_GLOBAL_INITIAL_SPREAD_VALUES=0.05 0.08 0.11 0.14"
SET "WUBU_D_GLOBAL_BOUNDARY_POINTS_PER_LEVEL=6 4 2 0"
SET "WUBU_D_GLOBAL_USE_ROTATION_FLAG=true"
SET "WUBU_D_GLOBAL_PHI_INFLUENCE_CURVATURE_FLAG=true"
SET "WUBU_D_GLOBAL_PHI_INFLUENCE_ROTATION_INIT_FLAG=true"
SET "DCT_GLOBAL_WUBU_D_INPUT_TANGENT_DIM=768"
SET "DCT_GLOBAL_WUBU_D_OUTPUT_FEATURE_DIM=256"
SET "DISC_USE_GLOBAL_STATS_AUX_DCT_GLOBAL_WUBU_FLAG=true"
SET "DISC_GLOBAL_STATS_MLP_HIDDEN_DIM_DCT_GLOBAL_WUBU=96"

REM ############################################################################
REM # SECTION: MultiModalWudioMelDiscriminator Specifics
REM ############################################################################
SET "WUDIO_D_USE_MEL_CNN_HEAD_FLAG=true"
SET "WUDIO_D_MEL_MSD_NUM_SCALES=3"
SET "WUDIO_D_MEL_MSD_SHARE_WEIGHTS_FLAG=false"
SET "WUDIO_D_MEL_CNN_BASE_CH=128"
SET "WUDIO_D_MEL_CNN_MAX_CH=1024"
SET "WUDIO_D_MEL_CNN_TARGET_DIM_H=4"
SET "WUDIO_D_MEL_CNN_TARGET_DIM_W=4"
SET "WUDIO_D_MEL_CNN_MAX_DOWNS=6"
SET "WUDIO_D_MEL_CNN_OUTPUT_FEAT_DIM_FOR_FUSION=384"
SET "WUDIO_D_MEL_USE_ATTENTION_FLAG=true"
SET "WUDIO_D_MEL_ATTENTION_IDX=2"
SET "WUDIO_D_MEL_SCALE0_USE_ATTENTION_FLAG=true"
SET "WUDIO_D_MEL_SCALE0_ATTENTION_IDX=2"
SET "WUDIO_D_MEL_SCALE1_USE_ATTENTION_FLAG=true"
SET "WUDIO_D_MEL_SCALE1_ATTENTION_IDX=1"
SET "WUDIO_D_MEL_SCALE2_USE_ATTENTION_FLAG=false"
REM SET "WUDIO_D_USE_STFT_HEAD_FLAG=false"
REM SET "WUDIO_D_STFT_OUTPUT_FEAT_DIM_FOR_FUSION=192"
SET "WUDIO_D_USE_GLOBAL_AUDIO_STATS_HEAD_FLAG=true"
SET "WUDIO_D_NUM_GLOBAL_AUDIO_STATS=8"
SET "WUDIO_D_GLOBAL_AUDIO_STATS_MLP_HIDDEN=96"
SET "WUDIO_D_GLOBAL_AUDIO_STATS_FEAT_DIM_FOR_FUSION=64"
SET "WUDIO_D_FUSION_METHOD=concat_linear"
SET "WUDIO_D_FUSION_MLP_HIDDEN_DIM=192"

REM ############################################################################
REM # SECTION: Q-Learning & Heuristics
REM ############################################################################
SET "Q_CONTROLLER_ENABLED_FLAG=true"
SET "RESET_Q_CONTROLLERS_ON_LOAD_FLAG=false"
SET "RESET_LKL_Q_CONTROLLER_ON_LOAD_FLAG=false"
SET "LAMBDA_KL_UPDATE_INTERVAL=10"
SET "MIN_LAMBDA_KL_Q_CONTROL=5e-4"
SET "MAX_LAMBDA_KL_Q_CONTROL=0.05"
SET "Q_LKL_SCALE_OPTIONS=0.6 0.8 1.0 1.2 1.4"
SET "Q_LKL_LR_MOM_PROBATION_STEPS=15"
SET "Q_LKL_ACTION_PROBATION_STEPS=15"

SET "ENABLE_HEURISTIC_INTERVENTIONS_FLAG=true"
SET "ENABLE_HEURISTIC_DISC_SWITCHING_FLAG=true"
SET "INITIAL_DISC_TYPE=mel"
SET "HEURISTIC_CHECK_INTERVAL=10"
SET "HEURISTIC_SHORT_TERM_HISTORY_LEN=7"
SET "HEURISTIC_TRIGGER_COUNT_THRESH=2"
SET "DISC_SWITCH_CHECK_INTERVAL=30"
SET "DISC_SWITCH_MIN_STEPS_BETWEEN=30"
SET "DISC_SWITCH_PROBLEM_STATE_COUNT_THRESH=2"
SET "HEURISTIC_D_STRONG_THRESH=0.20"
SET "HEURISTIC_D_WEAK_THRESH=1.2"
SET "HEURISTIC_D_VERY_WEAK_THRESH=2.0"
SET "HEURISTIC_G_STALLED_THRESH=1.8"
SET "HEURISTIC_G_WINNING_THRESH=0.15"
SET "HEURISTIC_G_VERY_MUCH_WINNING_THRESH=0.03"
SET "HEURISTIC_KL_HIGH_THRESH=15.0"
SET "HEURISTIC_RECON_STAGNATION_IMPROVEMENT_THRESH_REL=0.001"
SET "TARGET_GOOD_RECON_THRESH_HEURISTIC=0.015"
SET "HEURISTIC_Q_REWARD_STAGNATION_THRESH=-0.3"
SET "HEURISTIC_RECON_BOOST_FACTOR=1.5"
SET "LAMBDA_FEAT_MATCH_HEURISTIC=1.0"
SET "LAMBDA_G_EASY_WIN_PENALTY_HEURISTIC=2.0"
SET "G_EASY_WIN_PENALTY_EPS_DENOM=1e-5"
SET "MAX_G_EASY_WIN_PENALTY_ABS=10.0"
SET "HEURISTIC_ACTIVE_D_LR_BOOST_FACTOR=2.0"
SET "HEURISTIC_D_Q_EXPLORE_BOOST_EPSILON=0.75"
SET "HEURISTIC_D_Q_EXPLORE_DURATION=15"
SET "HEURISTIC_MIN_LAMBDA_GAN_FACTOR=0.5"
SET "HEURISTIC_MAX_LAMBDA_GAN_FACTOR=1.5"

REM ############################################################################
REM # SECTION: General Training Settings & Logging (from batch script)
REM ############################################################################
SET "TRAIN_SEED=1337"
SET "TRAIN_NUM_WORKERS=6"
SET "USE_AMP_FLAG=true"
SET "DETECT_ANOMALY_FLAG=false"
SET "DDP_FIND_UNUSED_PARAMS_G_FLAG=true"
SET "DDP_FIND_UNUSED_PARAMS_D_FLAG=true"
SET "FORCE_START_EPOCH_ON_LOAD_VALUE="
SET "FORCE_START_GSTEP_ON_LOAD_VALUE="
SET "DISABLE_VAL_TQDM_FLAG=false"

SET "LOG_INTERVAL=1"
SET "SAVE_INTERVAL=2000"
SET "SAVE_EPOCH_INTERVAL=1"
SET "VALIDATION_INTERVAL_EPOCHS=1"
SET "USE_LPIPS_FOR_MEL_VERIFICATION_FLAG=true"
SET "VAL_PRIMARY_METRIC=avg_val_lpips_mel"
SET "NUM_VAL_SAMPLES_TO_LOG=6"
SET "DEMO_NUM_SAMPLES=8"

SET "WANDB_ENABLED_FLAG=true"
SET "WANDB_PROJECT=WuBuSpecTransV011_AdvancedDs"
SET "WANDB_RUN_NAME=%RUN_NAME_SUFFIX%_SR%SAMPLE_RATE%_Lat%LATENT_DIM%_Mel%N_MELS%_Reg%GAAD_NUM_REGIONS%"
SET "WANDB_LOG_TRAIN_RECON_INTERVAL=20"
SET "TRAIN_TARGET_LOG_FREQ_MULTIPLIER=3"
SET "WANDB_LOG_FIXED_NOISE_INTERVAL=50"

REM ############################################################################
REM # SECTION: Construct Script Arguments
REM ############################################################################
SET "SCRIPT_ARGS="
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --audio_dir_path "!AUDIO_DATA_PATH!""
IF DEFINED VALIDATION_AUDIO_PATH ( IF NOT "!VALIDATION_AUDIO_PATH!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --validation_audio_dir_path "!VALIDATION_AUDIO_PATH!"" )
IF DEFINED LOAD_CHECKPOINT_VALUE ( IF NOT "!LOAD_CHECKPOINT_VALUE!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --load_checkpoint "!LOAD_CHECKPOINT_VALUE!"" )
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --checkpoint_dir "!CHECKPOINT_OUTPUT_DIR!""
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --seed !TRAIN_SEED!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --num_workers !TRAIN_NUM_WORKERS!"
IF /I "!USE_AMP_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --use_amp"
IF /I "!DETECT_ANOMALY_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --detect_anomaly"
IF /I "!DDP_FIND_UNUSED_PARAMS_G_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --ddp_find_unused_params_g"
IF /I "!DDP_FIND_UNUSED_PARAMS_D_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --ddp_find_unused_params_d"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --epochs !EPOCHS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --batch_size !BATCH_SIZE_PER_GPU!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --grad_accum_steps !GRAD_ACCUM_STEPS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --learning_rate_gen !LEARNING_RATE_GEN!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --learning_rate_disc !LEARNING_RATE_DISC!"
IF DEFINED LEARNING_RATE_DISC_ALT ( IF NOT "!LEARNING_RATE_DISC_ALT!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --learning_rate_disc_alt !LEARNING_RATE_DISC_ALT!" )
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --risgd_max_grad_norm !RISGD_MAX_GRAD_NORM!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --global_max_grad_norm !GLOBAL_MAX_GRAD_NORM!"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --lambda_recon !LAMBDA_RECON!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --lambda_kl !LAMBDA_KL!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --lambda_gan !LAMBDA_GAN!"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --sample_rate !SAMPLE_RATE!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --n_fft !N_FFT!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --hop_length !HOP_LENGTH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --n_mels !N_MELS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --fmin !FMIN!"
IF DEFINED FMAX ( IF NOT "!FMAX!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --fmax !FMAX!" )
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --segment_duration_sec !SEGMENT_DURATION_SEC!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --segment_overlap_sec !SEGMENT_OVERLAP_SEC!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --db_norm_min !DB_NORM_MIN!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --db_norm_max !DB_NORM_MAX!"
IF /I "!PRELOAD_AUDIO_DATASET_TO_RAM_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --preload_audio_dataset_to_ram"
IF /I "!DATASET_YIELD_RAW_AUDIO_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --dataset_yield_raw_audio"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --validation_split_fraction !VALIDATION_SPLIT_FRACTION!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --data_fraction !DATA_FRACTION!"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --vae_transform_type !VAE_TRANSFORM_TYPE!"
IF /I "!VAE_TRANSFORM_TYPE!"=="complex_dft_ri" (
    SET "SCRIPT_ARGS=!SCRIPT_ARGS! --dft_fft_norm !DFT_FFT_NORM!"
    SET "SCRIPT_ARGS=!SCRIPT_ARGS! --dft_complex_norm_scale !DFT_COMPLEX_NORM_SCALE!"
) ELSE IF /I "!VAE_TRANSFORM_TYPE!"=="dct" (
    SET "SCRIPT_ARGS=!SCRIPT_ARGS! --dct_norm_type !DCT_NORM_TYPE_IF_USED!"
    SET "SCRIPT_ARGS=!SCRIPT_ARGS! --dct_norm_global_scale !DCT_NORM_GLOBAL_SCALE_IF_USED!"
    SET "SCRIPT_ARGS=!SCRIPT_ARGS! --dct_norm_tanh_scale !DCT_NORM_TANH_SCALE_IF_USED!"
)

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --gaad_num_regions !GAAD_NUM_REGIONS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --gaad_decomposition_type !GAAD_DECOMP_TYPE!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --gaad_min_size_px !GAAD_MIN_SIZE_PX!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --region_proc_size_t !REGION_PROC_SIZE_T!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --region_proc_size_f !REGION_PROC_SIZE_F!"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --latent_dim !LATENT_DIM!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --encoder_initial_tangent_dim !ENCODER_INITIAL_TANGENT_DIM!"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --primary_disc_architecture_variant !PRIMARY_DISC_ARCHITECTURE_VARIANT!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --alt_disc_architecture_variant !ALT_DISC_ARCHITECTURE_VARIANT!"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_input_type !DISC_INPUT_TYPE_DEFAULT!"
IF /I "!DISC_APPLY_SPECTRAL_NORM_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_apply_spectral_norm"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_base_disc_channels !DISC_BASE_DISC_CHANNELS_DEFAULT!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_max_disc_channels !DISC_MAX_DISC_CHANNELS_DEFAULT!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_target_final_feature_dim !DISC_TARGET_FINAL_FEATURE_DIM_H_DEFAULT! !DISC_TARGET_FINAL_FEATURE_DIM_W_DEFAULT!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --max_mel_disc_downsample_layers !MAX_MEL_DISC_DOWNSAMPLE_LAYERS_DEFAULT!"
IF /I "!USE_MEL_D_ATTENTION_DEFAULT!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --use_mel_d_attention"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --mel_d_attention_idx !MEL_D_ATTENTION_IDX_DEFAULT!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --mel_d_msd_num_scales !MEL_D_MSD_NUM_SCALES_DEFAULT!"
IF /I "!MEL_D_MSD_SHARE_WEIGHTS_DEFAULT!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --mel_d_msd_share_weights"
IF DEFINED DISC_DCT_EMBED_DIM_DEFAULT ( IF NOT "!DISC_DCT_EMBED_DIM_DEFAULT!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_dct_embed_dim !DISC_DCT_EMBED_DIM_DEFAULT!" )
IF /I "!DISC_DCT_USE_POS_EMBED_DEFAULT!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_dct_use_pos_embed"
IF /I "!DISC_DCT_USE_CLS_TOKEN_DEFAULT!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_dct_use_cls_token"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_transformer_nhead !DISC_TRANSFORMER_NHEAD_DEFAULT!"
IF DEFINED DISC_TRANSFORMER_DIM_FEEDFORWARD_DEFAULT ( IF NOT "!DISC_TRANSFORMER_DIM_FEEDFORWARD_DEFAULT!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_transformer_dim_feedforward !DISC_TRANSFORMER_DIM_FEEDFORWARD_DEFAULT!" )
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_transformer_dropout !DISC_TRANSFORMER_DROPOUT_DEFAULT!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_transformer_num_layers !DISC_TRANSFORMER_NUM_LAYERS_DEFAULT!"
IF /I "!DISC_TRANSFORMER_NORM_FIRST_DEFAULT!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_transformer_norm_first"
IF /I "!DISC_USE_GLOBAL_STATS_AUX_DEFAULT!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_use_global_stats_aux"
IF DEFINED DISC_GLOBAL_STATS_MLP_HIDDEN_DIM_DEFAULT ( IF NOT "!DISC_GLOBAL_STATS_MLP_HIDDEN_DIM_DEFAULT!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_global_stats_mlp_hidden_dim !DISC_GLOBAL_STATS_MLP_HIDDEN_DIM_DEFAULT!" )

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_dropout !WUBU_DROPOUT!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_num_levels !WUBU_S_NUM_LEVELS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_hyperbolic_dims !WUBU_S_HYPERBOLIC_DIMS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_initial_curvatures !WUBU_S_INITIAL_CURVATURES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_initial_scales !WUBU_S_INITIAL_SCALES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_initial_spread_values !WUBU_S_INITIAL_SPREAD_VALUES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_boundary_points_per_level !WUBU_S_BOUNDARY_POINTS_PER_LEVEL!"
IF /I "!WUBU_S_USE_ROTATION_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_use_rotation"
IF /I "!WUBU_S_PHI_INFLUENCE_CURVATURE_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_phi_influence_curvature"
IF /I "!WUBU_S_PHI_INFLUENCE_ROTATION_INIT_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_phi_influence_rotation_init"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_s_output_dim_encoder !WUBU_S_OUTPUT_DIM_ENCODER!"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_g_num_levels !WUBU_G_NUM_LEVELS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_g_hyperbolic_dims !WUBU_G_HYPERBOLIC_DIMS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_g_initial_curvatures !WUBU_G_INITIAL_CURVATURES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_g_initial_scales !WUBU_G_INITIAL_SCALES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_g_initial_spread_values !WUBU_G_INITIAL_SPREAD_VALUES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_g_boundary_points_per_level !WUBU_G_BOUNDARY_POINTS_PER_LEVEL!"
IF /I "!WUBU_G_USE_ROTATION_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_g_use_rotation"
IF /I "!WUBU_G_PHI_INFLUENCE_CURVATURE_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_g_phi_influence_curvature"
IF /I "!WUBU_G_PHI_INFLUENCE_ROTATION_INIT_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_g_phi_influence_rotation_init"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_num_levels !WUBU_D_REGION_NUM_LEVELS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_feature_dim !WUBU_D_REGION_FEATURE_DIM!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_hyperbolic_dims !WUBU_D_REGION_HYPERBOLIC_DIMS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_initial_curvatures !WUBU_D_REGION_INITIAL_CURVATURES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_initial_scales !WUBU_D_REGION_INITIAL_SCALES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_initial_spread_values !WUBU_D_REGION_INITIAL_SPREAD_VALUES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_boundary_points_per_level !WUBU_D_REGION_BOUNDARY_POINTS_PER_LEVEL!"
IF /I "!WUBU_D_REGION_USE_ROTATION_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_use_rotation"
IF /I "!WUBU_D_REGION_PHI_INFLUENCE_CURVATURE_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_phi_influence_curvature"
IF /I "!WUBU_D_REGION_PHI_INFLUENCE_ROTATION_INIT_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_region_phi_influence_rotation_init"

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_global_num_levels !WUBU_D_GLOBAL_NUM_LEVELS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_global_hyperbolic_dims !WUBU_D_GLOBAL_HYPERBOLIC_DIMS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_global_initial_curvatures !WUBU_D_GLOBAL_INITIAL_CURVATURES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_global_initial_scales !WUBU_D_GLOBAL_INITIAL_SCALES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_global_initial_spread_values !WUBU_D_GLOBAL_INITIAL_SPREAD_VALUES!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_global_boundary_points_per_level !WUBU_D_GLOBAL_BOUNDARY_POINTS_PER_LEVEL!"
IF /I "!WUBU_D_GLOBAL_USE_ROTATION_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_global_use_rotation"
IF /I "!WUBU_D_GLOBAL_PHI_INFLUENCE_CURVATURE_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_global_phi_influence_curvature"
IF /I "!WUBU_D_GLOBAL_PHI_INFLUENCE_ROTATION_INIT_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wubu_d_global_phi_influence_rotation_init"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --dct_global_wubu_d_input_tangent_dim !DCT_GLOBAL_WUBU_D_INPUT_TANGENT_DIM!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --dct_global_wubu_d_output_feature_dim !DCT_GLOBAL_WUBU_D_OUTPUT_FEATURE_DIM!"
IF /I "!DISC_USE_GLOBAL_STATS_AUX_DCT_GLOBAL_WUBU_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_use_global_stats_aux_dct_global_wubu"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_global_stats_mlp_hidden_dim_dct_global_wubu !DISC_GLOBAL_STATS_MLP_HIDDEN_DIM_DCT_GLOBAL_WUBU!"

IF /I "!WUDIO_D_USE_MEL_CNN_HEAD_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_use_mel_cnn_head"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_msd_num_scales !WUDIO_D_MEL_MSD_NUM_SCALES!"
IF /I "!WUDIO_D_MEL_MSD_SHARE_WEIGHTS_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_msd_share_weights"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_cnn_base_ch !WUDIO_D_MEL_CNN_BASE_CH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_cnn_max_ch !WUDIO_D_MEL_CNN_MAX_CH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_cnn_target_dim !WUDIO_D_MEL_CNN_TARGET_DIM_H! !WUDIO_D_MEL_CNN_TARGET_DIM_W!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_cnn_max_downs !WUDIO_D_MEL_CNN_MAX_DOWNS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_cnn_output_feat_dim_for_fusion !WUDIO_D_MEL_CNN_OUTPUT_FEAT_DIM_FOR_FUSION!"
IF /I "!WUDIO_D_MEL_USE_ATTENTION_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_use_attention"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_attention_idx !WUDIO_D_MEL_ATTENTION_IDX!"
IF /I "!WUDIO_D_MEL_SCALE0_USE_ATTENTION_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_scale0_use_attention"
IF DEFINED WUDIO_D_MEL_SCALE0_ATTENTION_IDX ( IF NOT "!WUDIO_D_MEL_SCALE0_ATTENTION_IDX!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_scale0_attention_idx !WUDIO_D_MEL_SCALE0_ATTENTION_IDX!" )
IF /I "!WUDIO_D_MEL_SCALE1_USE_ATTENTION_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_scale1_use_attention"
IF DEFINED WUDIO_D_MEL_SCALE1_ATTENTION_IDX ( IF NOT "!WUDIO_D_MEL_SCALE1_ATTENTION_IDX!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_scale1_attention_idx !WUDIO_D_MEL_SCALE1_ATTENTION_IDX!" )
IF /I "!WUDIO_D_MEL_SCALE2_USE_ATTENTION_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_mel_scale2_use_attention"
REM IF /I "%WUDIO_D_USE_STFT_HEAD_FLAG%"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_use_stft_head"
REM SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_stft_output_feat_dim_for_fusion %WUDIO_D_STFT_OUTPUT_FEAT_DIM_FOR_FUSION%"
IF /I "!WUDIO_D_USE_GLOBAL_AUDIO_STATS_HEAD_FLAG!"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_use_global_audio_stats_head"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_num_global_audio_stats !WUDIO_D_NUM_GLOBAL_AUDIO_STATS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_global_audio_stats_mlp_hidden !WUDIO_D_GLOBAL_AUDIO_STATS_MLP_HIDDEN!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_global_audio_stats_feat_dim_for_fusion !WUDIO_D_GLOBAL_AUDIO_STATS_FEAT_DIM_FOR_FUSION!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_fusion_method !WUDIO_D_FUSION_METHOD!"
IF DEFINED WUDIO_D_FUSION_MLP_HIDDEN_DIM ( IF NOT "!WUDIO_D_FUSION_MLP_HIDDEN_DIM!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wudio_d_fusion_mlp_hidden_dim !WUDIO_D_FUSION_MLP_HIDDEN_DIM!" )

IF /I "%Q_CONTROLLER_ENABLED_FLAG%"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --q_controller_enabled"
IF /I "%RESET_Q_CONTROLLERS_ON_LOAD_FLAG%"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --reset_q_controllers_on_load"
IF /I "%RESET_LKL_Q_CONTROLLER_ON_LOAD_FLAG%"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --reset_lkl_q_controller_on_load"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --lambda_kl_update_interval !LAMBDA_KL_UPDATE_INTERVAL!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --min_lambda_kl_q_control !MIN_LAMBDA_KL_Q_CONTROL!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --max_lambda_kl_q_control !MAX_LAMBDA_KL_Q_CONTROL!"
IF DEFINED Q_LKL_SCALE_OPTIONS ( IF NOT "!Q_LKL_SCALE_OPTIONS!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --q_lkl_scale_options !Q_LKL_SCALE_OPTIONS!" )
IF DEFINED Q_LKL_LR_MOM_PROBATION_STEPS ( IF NOT "!Q_LKL_LR_MOM_PROBATION_STEPS!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --q_lkl_lr_mom_probation_steps !Q_LKL_LR_MOM_PROBATION_STEPS!" )
IF DEFINED Q_LKL_ACTION_PROBATION_STEPS ( IF NOT "!Q_LKL_ACTION_PROBATION_STEPS!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --q_lkl_action_probation_steps !Q_LKL_ACTION_PROBATION_STEPS!" )

IF /I "%ENABLE_HEURISTIC_INTERVENTIONS_FLAG%"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --enable_heuristic_interventions"
IF /I "%ENABLE_HEURISTIC_DISC_SWITCHING_FLAG%"=="true" (
    SET "SCRIPT_ARGS=!SCRIPT_ARGS! --enable_heuristic_disc_switching"
    IF DEFINED INITIAL_DISC_TYPE ( IF NOT "!INITIAL_DISC_TYPE!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --initial_disc_type !INITIAL_DISC_TYPE!" )
)
IF DEFINED HEURISTIC_CHECK_INTERVAL ( IF NOT "!HEURISTIC_CHECK_INTERVAL!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_check_interval !HEURISTIC_CHECK_INTERVAL!" ) ELSE ( SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_check_interval !LOG_INTERVAL!" )
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_short_term_history_len !HEURISTIC_SHORT_TERM_HISTORY_LEN!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_trigger_count_thresh !HEURISTIC_TRIGGER_COUNT_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_switch_check_interval !DISC_SWITCH_CHECK_INTERVAL!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_switch_min_steps_between !DISC_SWITCH_MIN_STEPS_BETWEEN!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disc_switch_problem_state_count_thresh !DISC_SWITCH_PROBLEM_STATE_COUNT_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_d_strong_thresh !HEURISTIC_D_STRONG_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_d_weak_thresh !HEURISTIC_D_WEAK_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_d_very_weak_thresh !HEURISTIC_D_VERY_WEAK_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_g_stalled_thresh !HEURISTIC_G_STALLED_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_g_winning_thresh !HEURISTIC_G_WINNING_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_g_very_much_winning_thresh !HEURISTIC_G_VERY_MUCH_WINNING_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_kl_high_thresh !HEURISTIC_KL_HIGH_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_recon_stagnation_improvement_thresh_rel !HEURISTIC_RECON_STAGNATION_IMPROVEMENT_THRESH_REL!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --target_good_recon_thresh_heuristic !TARGET_GOOD_RECON_THRESH_HEURISTIC!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_q_reward_stagnation_thresh !HEURISTIC_Q_REWARD_STAGNATION_THRESH!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_recon_boost_factor !HEURISTIC_RECON_BOOST_FACTOR!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --lambda_feat_match_heuristic !LAMBDA_FEAT_MATCH_HEURISTIC!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --lambda_g_easy_win_penalty_heuristic !LAMBDA_G_EASY_WIN_PENALTY_HEURISTIC!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --g_easy_win_penalty_eps_denom !G_EASY_WIN_PENALTY_EPS_DENOM!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --max_g_easy_win_penalty_abs !MAX_G_EASY_WIN_PENALTY_ABS!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_active_d_lr_boost_factor !HEURISTIC_ACTIVE_D_LR_BOOST_FACTOR!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_d_q_explore_boost_epsilon !HEURISTIC_D_Q_EXPLORE_BOOST_EPSILON!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_d_q_explore_duration !HEURISTIC_D_Q_EXPLORE_DURATION!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_min_lambda_gan_factor !HEURISTIC_MIN_LAMBDA_GAN_FACTOR!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --heuristic_max_lambda_gan_factor !HEURISTIC_MAX_LAMBDA_GAN_FACTOR!"
IF DEFINED FORCE_START_EPOCH_ON_LOAD_VALUE ( IF NOT "!FORCE_START_EPOCH_ON_LOAD_VALUE!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --force_start_epoch_on_load !FORCE_START_EPOCH_ON_LOAD_VALUE!" )
IF DEFINED FORCE_START_GSTEP_ON_LOAD_VALUE ( IF NOT "!FORCE_START_GSTEP_ON_LOAD_VALUE!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --force_start_gstep_on_load !FORCE_START_GSTEP_ON_LOAD_VALUE!" )

SET "SCRIPT_ARGS=!SCRIPT_ARGS! --log_interval !LOG_INTERVAL!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --save_interval !SAVE_INTERVAL!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --save_epoch_interval !SAVE_EPOCH_INTERVAL!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --validation_interval_epochs !VALIDATION_INTERVAL_EPOCHS!"
IF /I "%DISABLE_VAL_TQDM_FLAG%"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --disable_val_tqdm"
IF /I "%USE_LPIPS_FOR_MEL_VERIFICATION_FLAG%"=="true" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --use_lpips_for_mel_verification"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --val_primary_metric !VAL_PRIMARY_METRIC!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --num_val_samples_to_log !NUM_VAL_SAMPLES_TO_LOG!"
SET "SCRIPT_ARGS=!SCRIPT_ARGS! --demo_num_samples !DEMO_NUM_SAMPLES!"

IF /I "%WANDB_ENABLED_FLAG%"=="true" (
    SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb --wandb_project !WANDB_PROJECT!"
    IF DEFINED WANDB_RUN_NAME ( IF NOT "!WANDB_RUN_NAME!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb_run_name "!WANDB_RUN_NAME!"" )
)
IF %WANDB_LOG_TRAIN_RECON_INTERVAL% GTR 0 SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb_log_train_recon_interval !WANDB_LOG_TRAIN_RECON_INTERVAL!"
IF DEFINED TRAIN_TARGET_LOG_FREQ_MULTIPLIER ( IF NOT "!TRAIN_TARGET_LOG_FREQ_MULTIPLIER!"=="" SET "SCRIPT_ARGS=!SCRIPT_ARGS! --train_target_log_freq_multiplier !TRAIN_TARGET_LOG_FREQ_MULTIPLIER!" )
IF %WANDB_LOG_FIXED_NOISE_INTERVAL% GTR 0 SET "SCRIPT_ARGS=!SCRIPT_ARGS! --wandb_log_fixed_noise_samples_interval !WANDB_LOG_FIXED_NOISE_INTERVAL!"


ECHO ======================================================
ECHO WuBuSpecTrans VAE-GAN - Audio Run (%RUN_NAME_SUFFIX%)
ECHO Python Executable: %PYTHON_EXE%
ECHO Python Script: %SCRIPT_NAME%
ECHO Checkpoint Output Directory: %CHECKPOINT_OUTPUT_DIR%
ECHO Loading Checkpoint Value: %LOAD_CHECKPOINT_VALUE%
ECHO Audio Data Source: %AUDIO_DATA_PATH%
IF DEFINED VALIDATION_AUDIO_PATH ( IF NOT "%VALIDATION_AUDIO_PATH%"=="" ECHO Validation Audio Source: %VALIDATION_AUDIO_PATH% ) ELSE ( ECHO Validation from Training Split: %VALIDATION_SPLIT_FRACTION% )
ECHO Primary D Arch Variant: %PRIMARY_DISC_ARCHITECTURE_VARIANT%
ECHO Alternative D Arch Variant: %ALT_DISC_ARCHITECTURE_VARIANT%
ECHO Heuristic D Switching Enabled: %ENABLE_HEURISTIC_DISC_SWITCHING_FLAG%
IF /I "%ENABLE_HEURISTIC_DISC_SWITCHING_FLAG%"=="true" ECHO Initial Active D Input Type for Switching Logic: %INITIAL_DISC_TYPE%
ECHO VAE Transform Type: %VAE_TRANSFORM_TYPE%
ECHO Dataset Yields Raw Audio: %DATASET_YIELD_RAW_AUDIO_FLAG%
ECHO Batch Size per GPU: %BATCH_SIZE_PER_GPU% (Global: %GLOBAL_BATCH_SIZE% / NPROC: %NPROC_PER_NODE%)
ECHO ======================================================
ECHO.

IF NOT EXIST "%PYTHON_EXE%" (
    ECHO ERROR: Python executable not found at %PYTHON_EXE%
    GOTO :EndScriptAllInDFTv2
)
SET "VENV_ACTIVATE_PATH="
FOR %%F IN ("%PYTHON_EXE%") DO SET "VENV_ACTIVATE_PATH=%%~dpFactivate.bat"
IF EXIST "%VENV_ACTIVATE_PATH%" (
    ECHO Activating virtual environment: %VENV_ACTIVATE_PATH%
    CALL "%VENV_ACTIVATE_PATH%"
    IF ERRORLEVEL 1 ( ECHO WARNING: Failed to activate venv, proceeding with system Python. )
) ELSE (
    ECHO No venv activate script found at expected path. Using system Python or current environment.
)
ECHO.

IF NOT EXIST "%CHECKPOINT_OUTPUT_DIR%" MKDIR "%CHECKPOINT_OUTPUT_DIR%"
IF NOT EXIST "%DATA_DIR_BASE%" MKDIR "%DATA_DIR_BASE%"
IF NOT EXIST "%AUDIO_DATA_PATH%" MKDIR "%AUDIO_DATA_PATH%"

ECHO Starting training script: %SCRIPT_NAME%
ECHO.
ECHO Full command to be executed:
ECHO "%PYTHON_EXE%" "%FULL_SCRIPT_PATH%" !SCRIPT_ARGS!
ECHO.

IF %NPROC_PER_NODE% EQU 1 (
    "%PYTHON_EXE%" "%FULL_SCRIPT_PATH%" !SCRIPT_ARGS!
) ELSE (
    ECHO Launching with torch.distributed.run for %NPROC_PER_NODE% processes.
    SET "TORCHRUN_CMD=%PYTHON_EXE% -m torch.distributed.run --nproc_per_node=%NPROC_PER_NODE% --master_port=29524"
    %TORCHRUN_CMD% "%FULL_SCRIPT_PATH%" !SCRIPT_ARGS!
)

SET "EXIT_CODE=%ERRORLEVEL%"
ECHO.
IF %EXIT_CODE% NEQ 0 (
    ECHO **************************************
    ECHO * SCRIPT FAILED with exit code %EXIT_CODE% *
    ECHO **************************************
) ELSE (
    ECHO ****************************************
    ECHO * SCRIPT FINISHED successfully *
    ECHO ****************************************
)

:EndScriptAllInDFTv2
IF DEFINED PROMPT_AFTER_RUN (
    IF /I "%PROMPT_AFTER_RUN%"=="true" PAUSE
) ELSE (
    TIMEOUT /T 25 /NOBREAK >nul
)
ENDLOCAL