// tok_check.c — Verify tokenizer encode/decode roundtrip
#include "wubu_tokenizer.h"
#include <stdio.h>
#include <string.h>

int main() {
    wubu_tokenizer_t tok;
    const char *path = "/home/wubu/models/Qwen3.6-35B-A3B-UD-IQ2_M.gguf";
    if (!wubu_tokenizer_init(&tok, path)) return 1;
    
    printf("Tokenizer: %d vocab, %d merges, BOS=%d, EOS=%d, PAD=%d\n",
           tok.vocab_size, tok.n_merges, tok.bos_id, tok.eos_id, tok.pad_id);
    
    // Test 1: encode/decode a simple sentence
    const char *test = "Hello world";
    int ids[64];
    int n = wubu_tokenizer_encode(&tok, test, ids, 64);
    printf("Encode '%s': %d tokens: ", test, n);
    for (int i = 0; i < n; i++) printf("%d ", ids[i]);
    printf("\n");
    
    char dec[256];
    int nd = wubu_tokenizer_decode(&tok, ids, n, dec, 255);
    dec[nd] = '\0';
    printf("Decode back: '%s'\n", dec);
    
    // Test 2: check specific token IDs generated by inference
    int test_ids[] = {88712, 188621, 77686, 24940, 6659, 96665, 128068, 98412, 128628};
    const char *tnames[] = {"Fo", "kaw", "urgeon", "apat", "ped", "异", "赡", "现场", "作品集"};
    for (int i = 0; i < 9; i++) {
        char buf[64];
        int n2 = wubu_tokenizer_decode(&tok, test_ids + i, 1, buf, 63);
        buf[n2] = '\0';
        printf("Token %d -> '%s' (expected '%s') %s\n", 
               test_ids[i], buf, tnames[i],
               strcmp(buf, tnames[i]) == 0 ? "✓" : "✗");
    }
    
    // Test 3: decode the full output sequence
    int seq[] = {248044, 16226, 88712, 128628, 98412};
    int ns = 5;
    char buf2[256];
    int n3 = wubu_tokenizer_decode(&tok, seq, ns, buf2, 255);
    buf2[n3] = '\0';
    printf("\nSequence decode: '%s'\n", buf2);
    
    wubu_tokenizer_free(&tok);
    return 0;
}
